### ISSUE TITLE
How can I compile freetype with emscripten?

### ISSUE THREAD

**Issue by Bradan** [juj/emscripten-freetype#1]
Hello,

I just tried to compile freetype with emscripten, but it fails with emconfigure ./configure

```
emconfigure ./configure

FreeType build system -- automatic system detection

The following settings are used:

  platform                    unix
  compiler                    /usr/lib/emscripten/emcc
  configuration directory     ./builds/unix
  configuration rules         ./builds/unix/unix.mk

If this does not correspond to your system or settings please remove the file
`config.mk' from this directory then read the INSTALL file for help.

Otherwise, simply type `make' again to build the library,
or `make refdoc' to build the API reference (the latter needs python).

cd builds/unix; /bin/sh ./configure 
/bin/sh: ./configure: Datei oder Verzeichnis nicht gefunden
builds/unix/detect.mk:86: die Regel für Ziel „setup“ scheiterte
make: *** [setup] Fehler 127
ERROR    root: Configure step failed with non-zero return code 2! Command line: ['./configure'] at [...]/emscripten-freetype
```

and emmake make:

```
config.mk:25: builds/unix/unix-def.mk: Datei oder Verzeichnis nicht gefunden
config.mk:26: builds/unix/unix-cc.mk: Datei oder Verzeichnis nicht gefunden
make: *** Keine Regel, um „builds/unix/unix-cc.mk“ zu erstellen.  Schluss.
```

"Datei oder Verzeichnis nicht gefunden" is equal to "File or directory not found".

Kind regards,
Bradan

**Comment by juj** [comment]
I don't have familiarity with using configure scripts, but I use cmake instead to build, by first creating a build directory where the build will be created to, and in that directory then running `emcmake cmake path/to/emscripten-freetype`. Using the freetype configure scripts for emscripten can possibly(?) require some contribution to upstream autotools/automake and/or freetype repositories if one would like to make that work.

**Comment by Bradan** [comment]
Hmm isn't a CMakeList.txt necessary for building it with cmake? Because there is no such file in this repository.

```
CMake Error: The source directory "[...]/emscripten-freetype" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
ERROR    root: Configure step failed with non-zero return code 1! Command line: ['cmake', '..', '-DCMAKE_TOOLCHAIN_FILE=/usr/lib/emscripten/cmake/Modules/Platform/Emscripten.cmake'] at [...]/emscripten-freetype/cbuild
```

**Comment by juj** [comment]
Thanks, indeed. I think I had used a CMakeLists.txt for FreeType from some other project while testing this branch, or taken it directly from upstream but not committed. I've now rebased this repository to latest upstream, which does add a CMakeLists.txt, and tested that the branch builds with cmake.
